name: CD Workflow
on:
  push:
    tags:
      - '*'

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    strategy:
      matrix:
        target:
          - id: mipsel
            name: mipsel-unknown-linux-gnu
            args: []
          - id: mips
            name: mips-unknown-linux-gnu
            args: []
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      # TODO: Use Rust 1.71 since MIPS GNU targets no longer receive Tier 2 support.
      # https://github.com/rust-lang/compiler-team/issues/648
      # https://github.com/cross-rs/cross/issues/1319
      - name: Set up rust
        uses: dtolnay/rust-toolchain@1.71
        with:
          targets: ${{ matrix.target.name }}
      - name: Set up cross
        run: |
          cargo install cross
      - name: Set up cargo-deb
        run: |
          cargo install cargo-deb
      - name: Build
        run: |
          cross build --release --target=${{ matrix.target.name }} ${{ join(matrix.target.args, ' ') }}
          cargo deb \
            --no-build \
            --no-strip \
            --target=${{ matrix.target.name }} \
            --output=target/${{ matrix.target.name }}/debian/prometheus-edgerouter-exporter_${{ matrix.target.id }}.deb
      - name: Upload
        uses: softprops/action-gh-release@v1
        with:
          files: target/${{ matrix.target.name }}/debian/prometheus-edgerouter-exporter_${{ matrix.target.id }}.deb
