name: CD Workflow
on:
  push:
    tags:
      - '*'

defaults:
  run:
    shell: bash

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    strategy:
      matrix:
        target:
          - id: mipsel
            name: mipsel-unknown-linux-gnu
            args: []
          - id: mips
            name: mips-unknown-linux-gnu
            args: []
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Set up rust
        uses: dtolnay/rust-toolchain@nightly
      - name: Set up cross
        uses: taiki-e/install-action@v2
        with:
          tool: cross
      - name: Set up cargo-deb
        uses: taiki-e/cache-cargo-install-action@v2
        with:
          tool: cargo-deb
      - name: Build
        run: |
          cross build --release --target=${{ matrix.target.name }} ${{ join(matrix.target.args, ' ') }}
          cargo deb \
            --no-build \
            --no-strip \
            --target=${{ matrix.target.name }} \
            --output=target/${{ matrix.target.name }}/debian/prometheus-edgerouter-exporter_${{ matrix.target.id }}.deb
      - name: Upload
        uses: softprops/action-gh-release@v2
        with:
          files: target/${{ matrix.target.name }}/debian/prometheus-edgerouter-exporter_${{ matrix.target.id }}.deb
