name: CD Workflow
on:
  push:
    tags:
      - '*'

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    strategy:
      matrix:
        target:
          - id: mipsel
            name: mipsel-unknown-linux-gnu
            args: []
          - id: mips
            name: mips-unknown-linux-gnu
            args: []
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Set up rust
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: ${{ matrix.target.name }}
      - name: Set up cross
        run: |
          cargo install cross
      - name: Build
        run: |
          cross build --release --target=${{ matrix.target.name }} ${{ join(matrix.target.args, ' ') }}
      - name: Rename
        run: |
          mv target/${{ matrix.target.name }}/release/edgerouter-exporter{,-${{ matrix.target.id }}}
      - name: Upload
        uses: softprops/action-gh-release@v1
        with:
          files: target/${{ matrix.target.name }}/release/edgerouter-exporter-${{ matrix.target.id }}
