name: CI Workflow
on:
  push:
    branches:
      - master
  pull_request:

defaults:
  run:
    shell: bash

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5
      - name: Set up reviewdog
        uses: reviewdog/action-setup@v1
      - name: Set up rust
        uses: dtolnay/rust-toolchain@nightly
        with:
          components: clippy
      - name: Run tests
        run: |
          cargo test --workspace
      - name: Run clippy
        if: ${{ always() }}
        env:
          REVIEWDOG_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          cargo clippy --tests --workspace --quiet --message-format=short --color=never 2>&1 |
            reviewdog -f=clippy -reporter=github-pr-annotations -filter-mode=nofilter -fail-level=any -tee
  build:
    name: Build (${{ matrix.target.id }})
    runs-on: ubuntu-latest
    strategy:
      matrix:
        target:
          - id: mipsel
            name: mipsel-unknown-linux-gnu
            args: []
          - id: mips
            name: mips-unknown-linux-gnu
            args: []
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5
      - name: Set up rust
        uses: dtolnay/rust-toolchain@nightly
      - name: Set up cross
        uses: taiki-e/install-action@v2
        with:
          tool: cross
      - name: Build
        run: |
          cross build --release --target=${{ matrix.target.name }} ${{ join(matrix.target.args, ' ') }}
